spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.flyway.enabled=false
oci.namespace=${OCI_NAMESPACE}
oci.bucket=${OCI_BUCKET}