--------------------------------------------------------------------------------
-- GeoRural DataHub — DDL do catálogo de ingestão
--------------------------------------------------------------------------------
-- Banco......: Oracle Database (Autonomous / ATP)
-- Encoding...: UTF-8 (AL32UTF8) — abra o arquivo em UTF-8 ou os acentos quebram
-- Escopo.....: Sprint 1 (US01, US02, US03), com a base já pronta para US04 e US05
-- Gerado em..: 2026-09-18
--
--------------------------------------------------------------------------------
-- O QUE ESTE SCRIPT CRIA
--------------------------------------------------------------------------------
-- Seis tabelas que formam o CATÁLOGO do data lake.
--
-- A ideia central: os arquivos de dados ficam no OCI Object Storage; o banco
-- guarda o conhecimento sobre eles — de que fonte vieram, qual o hash, em que
-- zona estão, qual execução os processou. Bucket sem catálogo é pasta
-- compartilhada; é o catálogo que faz dele um data lake.
--
--   fonte                origem dos dados (CAR, IBGE, INPE, IBAMA...)
--   arquivo_bruto        cada arquivo recebido, na zona bruta
--   execucao             cada passagem do pipeline sobre um arquivo
--   registro_quarentena  linhas que reprovaram na validação
--   dataset_versao       versões de conjunto tratado/publicado
--   indicador_imovel     indicadores calculados por imóvel
--
--------------------------------------------------------------------------------
-- O QUE ESTE SCRIPT **NÃO** CRIA
--------------------------------------------------------------------------------
-- Nada de usuário, perfil, auditoria ou controle de acesso (US06).
-- Geometria e imóvel rural: ver V2__imovel_rural_geometria.sql
--
--------------------------------------------------------------------------------
-- COMO RODAR
--------------------------------------------------------------------------------
-- De cima para baixo, uma vez, num schema vazio. As seções 1 a 4 dependem da
-- ordem. A seção 0 é destrutiva e está comentada de propósito.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- SEÇÃO 0 — LIMPEZA (SOMENTE EM AMBIENTE DE DESENVOLVIMENTO)
--------------------------------------------------------------------------------
-- Descomente para recriar o schema do zero. NUNCA rode isso com dado real:
-- o CASCADE CONSTRAINTS PURGE apaga tudo e não vai para a lixeira.
--------------------------------------------------------------------------------
/*
BEGIN
  FOR t IN (
    SELECT table_name
      FROM user_tables
     WHERE table_name IN ('INDICADOR_IMOVEL','DATASET_VERSAO','REGISTRO_QUARENTENA',
                          'EXECUCAO','ARQUIVO_BRUTO','FONTE')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/
*/


--------------------------------------------------------------------------------
-- SEÇÃO 1 — TABELAS
--------------------------------------------------------------------------------

-- 1.1 FONTE ------------------------------------------------------------------
-- De onde os dados vêm. Cadastrada pelo Operador de Dados antes de qualquer
-- importação (US01). A sigla é chave de negócio: a API responde 409 quando o
-- usuário tenta cadastrar uma sigla que já existe.
CREATE TABLE fonte (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nome           VARCHAR2(160 CHAR) NOT NULL,
  sigla          VARCHAR2(12  CHAR) NOT NULL,
  orgao          VARCHAR2(160 CHAR) NOT NULL,
  formato        VARCHAR2(20  CHAR) NOT NULL,
  periodicidade  VARCHAR2(20  CHAR) DEFAULT 'eventual' NOT NULL,
  ativa          NUMBER(1)          DEFAULT 1 NOT NULL,
  criada_em      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_fonte         PRIMARY KEY (id),
  CONSTRAINT uk_fonte_sigla   UNIQUE (sigla),
  CONSTRAINT ck_fonte_ativa   CHECK (ativa IN (0,1)),
  CONSTRAINT ck_fonte_formato CHECK (formato IN ('CSV','GeoJSON','SHP','XLSX','JSON'))
);


-- 1.2 ARQUIVO_BRUTO ----------------------------------------------------------
-- Um registro por arquivo recebido. O arquivo em si mora no Object Storage;
-- aqui fica o ponteiro (chave_objeto) e a prova de integridade (hash_sha256).
--
-- A chave segue o padrão  bruta/<sigla>/<data>/<uuid>_<nome_original>
-- O UUID garante que dois envios do mesmo arquivo nunca se sobrescrevam — a
-- zona bruta é imutável por definição, é a prova de origem.
CREATE TABLE arquivo_bruto (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  fonte_id       NUMBER              NOT NULL,
  chave_objeto   VARCHAR2(1024 CHAR) NOT NULL,
  nome_original  VARCHAR2(260  CHAR) NOT NULL,
  tamanho_bytes  NUMBER(19)          NOT NULL,
  content_type   VARCHAR2(120  CHAR),
  hash_sha256    VARCHAR2(64   CHAR) NOT NULL,
  status         VARCHAR2(20   CHAR) DEFAULT 'PENDENTE' NOT NULL,
  recebido_em    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  processado_em  TIMESTAMP WITH TIME ZONE,
  CONSTRAINT pk_arquivo_bruto  PRIMARY KEY (id),
  CONSTRAINT fk_arquivo_fonte  FOREIGN KEY (fonte_id) REFERENCES fonte (id),
  CONSTRAINT uk_arquivo_chave  UNIQUE (chave_objeto),
  CONSTRAINT ck_arquivo_status CHECK (status IN
        ('PENDENTE','RECEBIDO','PROCESSANDO','PROCESSADO','REJEITADO')),
  CONSTRAINT ck_arquivo_tamanho CHECK (tamanho_bytes >= 0)
);


-- 1.3 EXECUCAO ---------------------------------------------------------------
-- Cada passagem do pipeline sobre um arquivo. ATENÇÃO À CARDINALIDADE:
-- a relação arquivo_bruto -> execucao. Um mesmo arquivo passa
-- por VALIDACAO, depois PADRONIZACAO, depois CRUZAMENTO, depois PUBLICACAO — é
-- para isso que existe a coluna `tipo`. Somando os retries, são várias linhas
-- por arquivo. Esta tabela é a linhagem que a US05 vai consultar.
CREATE TABLE execucao (
  id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  arquivo_bruto_id    NUMBER            NOT NULL,
  tipo                VARCHAR2(20 CHAR) NOT NULL,
  status              VARCHAR2(20 CHAR) DEFAULT 'EM_ANDAMENTO' NOT NULL,
  hash_execucao       VARCHAR2(64  CHAR),
  dag_run_id          VARCHAR2(120 CHAR),
  registros_lidos     NUMBER(12),
  registros_validos   NUMBER(12),
  registros_invalidos NUMBER(12),
  iniciada_em         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  finalizada_em       TIMESTAMP WITH TIME ZONE,
  mensagem_erro       VARCHAR2(4000 CHAR),
  CONSTRAINT pk_execucao        PRIMARY KEY (id),
  CONSTRAINT fk_execucao_arq    FOREIGN KEY (arquivo_bruto_id) REFERENCES arquivo_bruto (id),
  CONSTRAINT ck_execucao_tipo   CHECK (tipo IN
        ('VALIDACAO','PADRONIZACAO','CRUZAMENTO','PUBLICACAO')),
  CONSTRAINT ck_execucao_status CHECK (status IN ('EM_ANDAMENTO','CONCLUIDA','FALHOU'))
);


-- 1.4 REGISTRO_QUARENTENA ----------------------------------------------------
-- As linhas que reprovaram na validação (US02). Guardamos o payload original
-- para que o dado possa ser corrigido e reprocessado sem voltar na fonte.
CREATE TABLE registro_quarentena (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  execucao_id   NUMBER             NOT NULL,
  numero_linha  NUMBER(12),
  campo         VARCHAR2(80  CHAR),
  motivo        VARCHAR2(400 CHAR) NOT NULL,
  payload       CLOB,
  CONSTRAINT pk_quarentena     PRIMARY KEY (id),
  CONSTRAINT fk_quarentena_exe FOREIGN KEY (execucao_id) REFERENCES execucao (id)
);


-- 1.5 DATASET_VERSAO ---------------------------------------------------------
-- Versões de um conjunto tratado ou publicado (US03, US05). Cada versão aponta
-- para o objeto correspondente no bucket e para a execução que a produziu.
--
-- Versão publicada NUNCA é editada. Correção gera uma versão nova; a anterior
-- continua consultável — é isso que permite comparar duas versões.
CREATE TABLE dataset_versao (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  conjunto      VARCHAR2(60   CHAR) NOT NULL,
  versao        NUMBER(6)           NOT NULL,
  execucao_id   NUMBER              NOT NULL,
  chave_objeto  VARCHAR2(1024 CHAR) NOT NULL,
  zona          VARCHAR2(12   CHAR) NOT NULL,
  registros     NUMBER(12),
  publicada_em  TIMESTAMP WITH TIME ZONE,
  CONSTRAINT pk_dataset_versao PRIMARY KEY (id),
  CONSTRAINT uk_dataset_versao UNIQUE (conjunto, versao),
  CONSTRAINT fk_dataset_exe    FOREIGN KEY (execucao_id) REFERENCES execucao (id),
  CONSTRAINT ck_dataset_zona   CHECK (zona IN ('TRATADA','PUBLICADA')),
  CONSTRAINT ck_dataset_versao_pos CHECK (versao > 0)
);


-- 1.6 INDICADOR_IMOVEL -------------------------------------------------------
-- Os sete indicadores ambientais calculados por imóvel (US04). O valor está
-- sempre amarrado à versão do conjunto que o produziu — é o que permite dizer
-- "este número saiu da versão 7, calculada pela execução X sobre o arquivo Y".
--
-- A coluna `regra` guarda o código da regra de negócio (RN-ICV-Bioma etc.),
-- que é o que torna o número auditável.
CREATE TABLE indicador_imovel (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  cod_imovel        VARCHAR2(80 CHAR) NOT NULL,
  dataset_versao_id NUMBER            NOT NULL,
  indicador         VARCHAR2(10 CHAR) NOT NULL,
  valor             NUMBER(14,4),
  unidade           VARCHAR2(12 CHAR),
  status            VARCHAR2(12 CHAR),
  regra             VARCHAR2(40 CHAR),
  CONSTRAINT pk_indicador     PRIMARY KEY (id),
  CONSTRAINT fk_indicador_ver FOREIGN KEY (dataset_versao_id) REFERENCES dataset_versao (id),
  CONSTRAINT uk_indicador     UNIQUE (cod_imovel, dataset_versao_id, indicador),
  CONSTRAINT ck_indicador_sig CHECK (indicador IN
        ('ICV','IRL','IAPP','ISAP','IAE','IDESMAT','IFC')),
  CONSTRAINT ck_indicador_st  CHECK (status IN ('CONFORME','ALERTA','CRITICO','VALIDACAO'))
);


--------------------------------------------------------------------------------
-- SEÇÃO 2 — ÍNDICES
--------------------------------------------------------------------------------
-- PK e UNIQUE já criam índice sozinhas. Estes cobrem os acessos que a aplicação
-- e o pipeline fazem com mais frequência.
--------------------------------------------------------------------------------

-- A fila do pipeline: "me dê tudo que está RECEBIDO, mais antigo primeiro"
CREATE INDEX ix_arquivo_status ON arquivo_bruto (status, recebido_em);

-- A tela de fontes: últimos arquivos de uma fonte
CREATE INDEX ix_arquivo_fonte ON arquivo_bruto (fonte_id, recebido_em DESC);

-- A linhagem de um arquivo (US05)
CREATE INDEX ix_execucao_arquivo ON execucao (arquivo_bruto_id, iniciada_em DESC);

-- Deduplicação do disparo vindo do Airflow
CREATE INDEX ix_execucao_dagrun ON execucao (dag_run_id);

-- Agrupamento de motivos de quarentena por execução
CREATE INDEX ix_quarentena_execucao ON registro_quarentena (execucao_id);

-- Consulta de indicadores de um imóvel
CREATE INDEX ix_indicador_imovel ON indicador_imovel (cod_imovel, indicador);


--------------------------------------------------------------------------------
-- SEÇÃO 3 — COMENTÁRIOS NO DICIONÁRIO DE DADOS
--------------------------------------------------------------------------------
-- Ficam visíveis em USER_TAB_COMMENTS / USER_COL_COMMENTS e em qualquer
-- ferramenta de modelagem. Comentamos só o que não é óbvio pelo nome.
--------------------------------------------------------------------------------

COMMENT ON TABLE fonte               IS 'Origem dos dados ambientais (CAR, IBGE, INPE, IBAMA). US01.';
COMMENT ON TABLE arquivo_bruto       IS 'Arquivo recebido e armazenado na zona bruta do Object Storage. US01.';
COMMENT ON TABLE execucao            IS 'Uma passagem do pipeline sobre um arquivo. Relação 1:N com arquivo_bruto. US02, US03, US05.';
COMMENT ON TABLE registro_quarentena IS 'Linhas reprovadas na validação, com o motivo e o dado original. US02.';
COMMENT ON TABLE dataset_versao      IS 'Versão imutável de um conjunto tratado ou publicado. US03, US05.';
COMMENT ON TABLE indicador_imovel    IS 'Indicador ambiental calculado por imóvel, amarrado à versão que o produziu. US04.';

COMMENT ON COLUMN fonte.sigla                   IS 'Chave de negócio, única. A API responde 409 em caso de duplicidade.';
COMMENT ON COLUMN fonte.ativa                   IS '1 = ativa, 0 = inativa. Oracle não tem BOOLEAN em SQL antes do 23ai.';

COMMENT ON COLUMN arquivo_bruto.chave_objeto    IS 'Caminho do objeto no bucket: bruta/<sigla>/<data>/<uuid>_<nome>. Imutável.';
COMMENT ON COLUMN arquivo_bruto.hash_sha256     IS 'SHA-256 calculado durante o upload. Prova de integridade da US01. Imutável.';
COMMENT ON COLUMN arquivo_bruto.status          IS 'PENDENTE -> RECEBIDO -> PROCESSANDO -> PROCESSADO | REJEITADO.';
COMMENT ON COLUMN arquivo_bruto.content_type    IS 'MIME type informado no upload. Meramente informativo.';

COMMENT ON COLUMN execucao.tipo                 IS 'Etapa do pipeline. É o motivo de a relação com arquivo_bruto ser 1:N.';
COMMENT ON COLUMN execucao.hash_execucao        IS 'Carimbo que amarra resultado -> execução -> entrada. Base da auditabilidade.';
COMMENT ON COLUMN execucao.dag_run_id           IS 'Id da execução no Airflow. Derivado do id do arquivo (arquivo-1842) para o disparo ser idempotente.';
COMMENT ON COLUMN execucao.mensagem_erro        IS 'Preenchido apenas quando status = FALHOU.';

COMMENT ON COLUMN registro_quarentena.payload   IS 'A linha original, para permitir correção sem voltar à fonte.';

COMMENT ON COLUMN dataset_versao.conjunto       IS 'imoveis_rurais, app_hidrografica, reserva_legal, uso_cobertura, municipios.';
COMMENT ON COLUMN dataset_versao.versao         IS 'Ordinal crescente por conjunto. Necessário para comparar versões (US05).';
COMMENT ON COLUMN dataset_versao.zona           IS 'TRATADA ou PUBLICADA. A zona também aparece no prefixo da chave_objeto.';

COMMENT ON COLUMN indicador_imovel.cod_imovel   IS 'Código CAR do imóvel. Sem FK de propósito — ver nota 5 do script.';
COMMENT ON COLUMN indicador_imovel.regra        IS 'Código da regra de negócio aplicada, por exemplo RN-ICV-Bioma.';
COMMENT ON COLUMN indicador_imovel.status       IS 'CONFORME, ALERTA, CRITICO ou VALIDACAO. É o que a interface usa para colorir.';


--------------------------------------------------------------------------------
-- SEÇÃO 4 — DADOS INICIAIS
--------------------------------------------------------------------------------
-- As quatro fontes que o front-end já usa no mock. Deixar o banco e o mock com
-- os mesmos dados evita surpresa na hora de trocar um pelo outro.
--------------------------------------------------------------------------------

INSERT INTO fonte (nome, sigla, orgao, formato, periodicidade)
VALUES ('CAR - Cadastro Ambiental Rural', 'CAR',
        'Servico Florestal Brasileiro', 'SHP', 'mensal');

INSERT INTO fonte (nome, sigla, orgao, formato, periodicidade)
VALUES ('IBGE - Malha municipal', 'IBGE',
        'Instituto Brasileiro de Geografia e Estatistica', 'GeoJSON', 'anual');

INSERT INTO fonte (nome, sigla, orgao, formato, periodicidade)
VALUES ('INPE - Alertas de desmatamento', 'INPE',
        'Instituto Nacional de Pesquisas Espaciais', 'CSV', 'diaria');

INSERT INTO fonte (nome, sigla, orgao, formato, periodicidade)
VALUES ('IBAMA - Embargos ambientais', 'IBAMA',
        'Instituto Brasileiro do Meio Ambiente', 'CSV', 'semanal');

COMMIT;

--------------------------------------------------------------------------------
-- FIM
--------------------------------------------------------------------------------
