--------------------------------------------------------------------------------
-- GeoRural DataHub — Imóvel Rural com geometria espacial
--------------------------------------------------------------------------------
-- Banco......: Oracle Database (Autonomous / ATP)
-- Encoding...: UTF-8 (AL32UTF8) — abra o arquivo em UTF-8 ou os acentos quebram
-- Escopo.....: US04 — visualizar imóveis rurais e divisões territoriais em mapa
-- Depende de.: V1__catalogo_ingestao.sql (tabela dataset_versao já criada)
-- Gerado em..: 2026-09-18
--
--------------------------------------------------------------------------------
-- O QUE ESTE SCRIPT CRIA
--------------------------------------------------------------------------------
-- Uma tabela: imovel_rural — a geometria (polígono) de cada imóvel, amarrada
-- à versão do dataset (CAR) que a originou, seguindo o mesmo padrão de
-- rastreabilidade já usado em indicador_imovel (V1).
--
-- SRID 4326 = WGS84 (lat/long), padrão pra dado geográfico vindo do CAR/IBGE.
--
--------------------------------------------------------------------------------
-- O QUE ESTE SCRIPT **NÃO** FAZ
--------------------------------------------------------------------------------
-- Não altera indicador_imovel. A FK opcional de indicador_imovel.cod_imovel
-- para imovel_rural.cod_imovel fica para uma V3 separada, decisão de time —
-- ver nota no final do arquivo.
--
--------------------------------------------------------------------------------
-- COMO RODAR
--------------------------------------------------------------------------------
-- Via Flyway, automaticamente na subida da aplicação, depois de V1.
-- Não editar este arquivo depois de aplicado em qualquer ambiente (quebra o
-- checksum do Flyway) — qualquer ajuste vira uma V3 nova.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- SEÇÃO 1 — TABELA
--------------------------------------------------------------------------------

-- 1.1 IMOVEL_RURAL ------------------------------------------------------------
-- Guarda a geometria de cada imóvel. dataset_versao_id amarra a geometria à
-- versão do conjunto que a produziu — mesmo raciocínio de auditabilidade que
-- indicador_imovel usa para os indicadores calculados.
CREATE TABLE imovel_rural (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  cod_imovel        VARCHAR2(80 CHAR)  NOT NULL,
  municipio         VARCHAR2(160 CHAR),
  estado            VARCHAR2(2 CHAR),
  area_ha           NUMBER(14,4),
  geometria         SDO_GEOMETRY       NOT NULL,
  dataset_versao_id NUMBER             NOT NULL,
  criado_em         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_imovel_rural  PRIMARY KEY (id),
  CONSTRAINT uk_imovel_cod    UNIQUE (cod_imovel),
  CONSTRAINT fk_imovel_versao FOREIGN KEY (dataset_versao_id) REFERENCES dataset_versao (id)
);


--------------------------------------------------------------------------------
-- SEÇÃO 2 — METADADO E ÍNDICE ESPACIAL
--------------------------------------------------------------------------------
-- O Oracle exige o registro em USER_SDO_GEOM_METADATA antes de aceitar criar
-- um índice espacial sobre a coluna. Sem o índice, qualquer consulta
-- geográfica (bounding box, interseção, distância) faz full table scan.
--------------------------------------------------------------------------------

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
  'IMOVEL_RURAL',
  'GEOMETRIA',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.005),
    SDO_DIM_ELEMENT('LATITUDE',  -90,   90, 0.005)
  ),
  4326
);
COMMIT;

CREATE INDEX ix_imovel_geometria ON imovel_rural (geometria)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;


--------------------------------------------------------------------------------
-- SEÇÃO 3 — COMENTÁRIOS NO DICIONÁRIO DE DADOS
--------------------------------------------------------------------------------

COMMENT ON TABLE imovel_rural IS 'Imóvel rural com geometria (polígono do CAR), amarrado à versão do dataset que o originou. US04.';

COMMENT ON COLUMN imovel_rural.cod_imovel        IS 'Código CAR do imóvel — mesmo valor referenciado em indicador_imovel.cod_imovel (V1).';
COMMENT ON COLUMN imovel_rural.geometria         IS 'Geometria espacial (SDO_GEOMETRY), SRID 4326 (WGS84 lat/long).';
COMMENT ON COLUMN imovel_rural.dataset_versao_id IS 'Versão do dataset (CAR) que originou esta geometria. FK para dataset_versao (V1).';
COMMENT ON COLUMN imovel_rural.estado            IS 'UF, 2 caracteres.';


--------------------------------------------------------------------------------
-- NOTA — FK opcional em indicador_imovel
--------------------------------------------------------------------------------
-- Agora que imovel_rural existe (com cod_imovel UNIQUE), é possível fechar a
-- referência que ficou em aberto no V1:
--
--   ALTER TABLE indicador_imovel
--     ADD CONSTRAINT fk_indicador_imovel
--     FOREIGN KEY (cod_imovel) REFERENCES imovel_rural (cod_imovel);
--
-- Deixado como comentário de propósito: aplicar isso é decisão de time (afeta
-- quem já trabalha com indicador_imovel) — se for aprovado, vira uma
-- V3__fk_indicador_imovel.sql própria, não uma edição deste arquivo.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- FIM
--------------------------------------------------------------------------------