--------------------------------------------------------------------------------
-- GeoRural DataHub — Município (Zona Tratada) e vínculo com imóvel rural
--------------------------------------------------------------------------------
-- Depende de.: V1 (dataset_versao) e V2 (imovel_rural, ix_imovel_geometria)
-- Escopo.....: US04 — divisões territoriais no mapa e cruzamento imóvel x municipio
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- SEÇÃO 1 — TABELA
--------------------------------------------------------------------------------
-- cod_ibge é a chave de negócio (7 dígitos); o id surrogate existe pelo mesmo
-- motivo dos demais: a FK não depende de o IBGE manter o código estável.
CREATE TABLE municipio (
  id                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  cod_ibge          VARCHAR2(7 CHAR)   NOT NULL,
  nome              VARCHAR2(160 CHAR) NOT NULL,
  estado            VARCHAR2(2 CHAR)   NOT NULL,
  regiao            VARCHAR2(20 CHAR),
  area_km2          NUMBER(14,4),
  geometria         SDO_GEOMETRY       NOT NULL,
  dataset_versao_id NUMBER             NOT NULL,
  criado_em         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_municipio        PRIMARY KEY (id),
  CONSTRAINT uk_municipio_ibge   UNIQUE (cod_ibge),
  CONSTRAINT fk_municipio_versao FOREIGN KEY (dataset_versao_id) REFERENCES dataset_versao (id),
  CONSTRAINT ck_municipio_ibge   CHECK (REGEXP_LIKE(cod_ibge, '^[0-9]{7}$')),
  CONSTRAINT ck_municipio_area   CHECK (area_km2 IS NULL OR area_km2 > 0),
  CONSTRAINT ck_municipio_uf     CHECK (estado IN
        ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG',
         'PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'))
);

--------------------------------------------------------------------------------
-- SEÇÃO 2 — METADADO E ÍNDICE ESPACIAL
--------------------------------------------------------------------------------
-- Mesmo SRID da V2 (4326): layers com SRID diferente não se cruzam sem
-- SDO_CS.TRANSFORM, e o cruzamento imóvel x município é o ponto da US04.
--
-- Tolerância 0.05: em SRID geodético o valor é em METROS, não graus, e 0.05
-- é o mínimo que a Oracle documenta para dado geodésico.
--
-- O COMMIT antes do CREATE INDEX é obrigatório: o índice espacial lê
-- USER_SDO_GEOM_METADATA em transação própria (ORA-13203 sem ele).
--------------------------------------------------------------------------------

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES (
  'MUNICIPIO',
  'GEOMETRIA',
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.05),
    SDO_DIM_ELEMENT('LATITUDE',  -90,   90, 0.05)
  ),
  4326
);
COMMIT;

CREATE INDEX ix_municipio_geometria ON municipio (geometria)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX ix_municipio_estado ON municipio (estado, nome);

--------------------------------------------------------------------------------
-- SEÇÃO 3 — VÍNCULO IMOVEL_RURAL -> MUNICIPIO
--------------------------------------------------------------------------------
-- Coluna anulável de propósito: a malha do IBGE ainda não foi carregada.
-- O pipeline preenche na etapa CRUZAMENTO, via SDO_RELATE.
--------------------------------------------------------------------------------

ALTER TABLE imovel_rural ADD (municipio_id NUMBER);

ALTER TABLE imovel_rural ADD CONSTRAINT fk_imovel_municipio
  FOREIGN KEY (municipio_id) REFERENCES municipio (id);

-- Oracle não indexa FK sozinho. Sem este índice, DELETE em municipio pega
-- lock de tabela em imovel_rural.
CREATE INDEX ix_imovel_municipio ON imovel_rural (municipio_id);

--------------------------------------------------------------------------------
-- SEÇÃO 4 — CORREÇÃO DA TOLERÂNCIA DE IMOVEL_RURAL (herdada da V2)
--------------------------------------------------------------------------------
-- A V2 gravou tolerância 0.005 num layer geodésico, onde o valor é lido em
-- METROS: 5 milímetros. DIMINFO não pode ser alterado com o índice montado —
-- derruba, corrige, remonta. Nesta ordem.
--------------------------------------------------------------------------------

DROP INDEX ix_imovel_geometria;

UPDATE USER_SDO_GEOM_METADATA
   SET DIMINFO = SDO_DIM_ARRAY(
         SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.05),
         SDO_DIM_ELEMENT('LATITUDE',  -90,   90, 0.05)
       )
 WHERE TABLE_NAME  = 'IMOVEL_RURAL'
   AND COLUMN_NAME = 'GEOMETRIA';
COMMIT;

CREATE INDEX ix_imovel_geometria ON imovel_rural (geometria)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--------------------------------------------------------------------------------
-- SEÇÃO 5 — COMENTÁRIOS NO DICIONÁRIO DE DADOS
--------------------------------------------------------------------------------

COMMENT ON TABLE municipio IS 'Malha municipal do IBGE na zona tratada, amarrada à versão do dataset que a originou. US04.';

COMMENT ON COLUMN municipio.cod_ibge          IS 'Código IBGE do município, 7 dígitos. Chave de negócio, única.';
COMMENT ON COLUMN municipio.geometria         IS 'Geometria espacial (SDO_GEOMETRY), SRID 4326 — mesmo SRID de imovel_rural.';
COMMENT ON COLUMN municipio.dataset_versao_id IS 'Versão do dataset (IBGE) que originou esta geometria. FK para dataset_versao (V1).';

COMMENT ON COLUMN imovel_rural.municipio_id   IS 'Município do imóvel, resolvido por interseção espacial na etapa CRUZAMENTO.';
COMMENT ON COLUMN imovel_rural.municipio      IS 'OBSOLETO: texto livre da fonte. Usar municipio_id.';
COMMENT ON COLUMN imovel_rural.estado         IS 'OBSOLETO: texto livre da fonte. Usar municipio_id -> municipio.estado.';

